services:
  backend:
    container_name: django
    image: django
    build: ./backend
    # volumes:
    #   - ./backend/ft_djoser:/app/ft_djoser
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network

  db:
    #image: postgres:13
    container_name: postgres
    image: postgres
    build: ./database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: ft_transcendence
    driver: bridge
